export const COUNTRIES = [
    { key: 'AFG', text: 'Afganistán' },
    { key: 'ALB', text: 'Albania' },
    { key: 'DZA', text: 'Argelia' },
    { key: 'AND', text: 'Andorra' },
    { key: 'AGO', text: 'Angola' },
    { key: 'ARG', text: 'Argentina' },
    { key: 'ARM', text: 'Armenia' },
    { key: 'AUS', text: 'Australia' },
    { key: 'AUT', text: 'Austria' },
    { key: 'AZE', text: 'Azerbaiyán' },
    { key: 'BGD', text: 'Bangladés' },
    { key: 'BLR', text: 'Bielorrusia' },
    { key: 'BEL', text: 'Bélgica' },
    { key: 'BOL', text: 'Bolivia' },
    { key: 'BRA', text: 'Brasil' },
    { key: 'BGR', text: 'Bulgaria' },
    { key: 'CAN', text: 'Canadá' },
    { key: 'CHL', text: 'Chile' },
    { key: 'CHN', text: 'China' },
    { key: 'COL', text: 'Colombia' },
    { key: 'CRI', text: 'Costa Rica' },
    { key: 'HRV', text: 'Croacia' },
    { key: 'CUB', text: 'Cuba' },
    { key: 'CZE', text: 'República Checa' },
    { key: 'DNK', text: 'Dinamarca' },
    { key: 'EGY', text: 'Egipto' },
    { key: 'SLV', text: 'El Salvador' },
    { key: 'FIN', text: 'Finlandia' },
    { key: 'FRA', text: 'Francia' },
    { key: 'DEU', text: 'Alemania' },
    { key: 'PER', text: 'Perú' },
    { key: 'MEX', text: 'México' },
    { key: 'ITA', text: 'Italia' }
];
