export const PAYMENT_METHODS = [
    { key: 'Oh-Visa', text: 'Oh-Visa | Tarjeta de Crédito Oh! Visa'},
    { key: 'Oh-Mastercard', text: 'Oh-Mastercard | Tarjeta de Crédito Oh! Mastercard'},
    { key: 'Tarjeta-Oh', text: 'Tarjeta-Oh | Tarjeta Oh! Visa y Mastercard'},
    { key: 'Tarjetas-Credito', text: 'Tarjetas-Credito | Tarjeta de Crédito'},
    { key: 'Tarjetas-Debito', text: 'Tarjetas-Debito | Tarjeta de Débito'},
    { key: 'Credito-Intercorp', text: 'Credito-Intercorp | Crédito Intercorp'},
    { key: 'Debito-Intercorp', text: 'Debito-Intercorp | Débito Intercorp'},
    { key: 'Tarjetas-Amex-VIVANDA', text: 'Tarjetas-Amex-VIVANDA | Tarjetas AMEX - VIVANDA'},
    { key: 'Tarjetas-Credito-Debito-VIVANDA', text: 'Tarjetas-Credito-Debito-VIVANDA | Tarjetas de Crédito o Débito - VIVANDA'},
    { key: 'Tarjetas-Credito-Debito-OECHSLE', text: 'Tarjetas-Credito-Debito-OECHSLE | Tarjetas de Crédito o Débito - OECHSLE'},
    { key: 'Tarjetas-Credito-Debito-PVEA', text: 'Tarjetas-Credito-Debito-PVEA | Tarjetas de Crédito o Débito - PLAZA VEA'},
    { key: 'Campana-Peru-Pasion', text: 'Campana-Peru-Pasion | Campana especial de Peru Pasion'},
    { key: 'Tarjetas-Visa', text: 'Tarjetas-Visa | Tarjetas Visa'},
    { key: 'Tarjetas-Mastercard', text: 'Tarjetas-Mastercard | Tarjetas Mastercard'},
    { key: 'Tarjetas-Amex', text: 'Tarjetas-Amex | Tarjetas Amex'},
    { key: 'Tarjetas-Diners', text: 'Tarjetas-Diners | Tarjetas Diners'},
    { key: 'Tarjeta-Agora-Visa', text: 'Tarjeta-Agora-Visa | Tarjeta Prepago Agora Visa'},
    { key: 'Tarjeta-Oh-Cuotas', text: 'Tarjeta-Oh-Cuotas | Tarjeta Oh! Visa y Mastercard Cuota'},
    { key: 'Tarjeta-Oh-Visa', text: 'Tarjeta-Oh-Visa | Tarjeta Oh Visa'},
    { key: 'Tarjeta-Oh-Mastercard', text: 'Tarjeta-Oh-Mastercard | Tarjeta Oh Mastercard'},
    { key: 'Tarjeta Oh!', text: 'Tarjeta Oh! | Tarjeta Oh!'},
    { key: 'Tarjetas-Credito-Debito-PROMART', text: 'Tarjetas-Credito-Debito-PROMART | Tarjetas de Crédito o Débito - PROMART'},
    { key: 'AGORAWEB', text: 'AGORAWEB | App Agora Pay'},
    { key: 'Tarjetas-Interbank-VIVANDA', text: 'Tarjetas-Interbank-VIVANDA | Tarjetas INTERBANK - VIVANDA'},
    { key: 'Tarjetas-IBK-Visa', text: 'Tarjetas-IBK-Visa | Tarjetas IBK Visa'},
    { key: 'Tarjetas-IBK-Mastercard', text: 'Tarjetas-IBK-Mastercard | Tarjetas IBK Mastercard'},
    { key: 'Tarjetas-IBK-Amex', text: 'Tarjetas-IBK-Amex | Tarjetas IBK Amex'},
    { key: 'Agora-Visa', text: 'Agora-Visa | Tarjeta Agora Visa'},
    { key: 'Tarjetas-Credito-Debito', text: 'Tarjetas-Credito-Debito | Tarjetas de Crédito o Débito'},
    { key: 'Tarjetas-Credito-Debito-PROM', text: 'Tarjetas-Credito-Debito-PROM | Tarjetas-Credito-Debito-PROM'},
    { key: 'AGORA', text: 'AGORA | Tarjetas de Crédito y Débito Agora Shop'},
    { key: 'Tarjetas-INTERBANK', text: 'Tarjetas-INTERBANK | Tarjetas INTERBANK'},
    { key: 'AGORA-UNIFICADO', text: 'Agora unificado'}
]
